#pragma once

#include "sdkconfig.h"

/*
 * Asset/font sources generated by lv_img_conv or lv_font_conv typically define
 * LV_ATTRIBUTE_MEM_ALIGN themselves if it is still undefined. Make sure that
 * by the time they check, we've already wired the macro to the alignment value
 * configured in menuconfig (CONFIG_LV_DRAW_BUF_ALIGN). That way the warning
 * emitted by lv_draw_buf_init() goes away without touching every generated file.
 */
#ifndef LV_ATTRIBUTE_MEM_ALIGN
#if defined(CONFIG_LV_DRAW_BUF_ALIGN) && (CONFIG_LV_DRAW_BUF_ALIGN > 0)
#define LV_ATTRIBUTE_MEM_ALIGN __attribute__((aligned(CONFIG_LV_DRAW_BUF_ALIGN)))
#else
#define LV_ATTRIBUTE_MEM_ALIGN
#endif
#endif
