#pragma once

// Intro animation timings (milliseconds)
#define THERMOSTAT_ANIM_LED_WHITE_FADE_IN_MS 400
#define THERMOSTAT_ANIM_LED_WHITE_HOLD_MS 2000
#define THERMOSTAT_ANIM_LED_BLACK_FADE_OUT_MS 1000
#define THERMOSTAT_ANIM_LED_BLACK_FADE_COMPLETE_BUFFER_MS 100
#define THERMOSTAT_ANIM_LED_BLACK_FADE_COMPLETE_DELAY_MS \
  (THERMOSTAT_ANIM_LED_BLACK_FADE_OUT_MS + THERMOSTAT_ANIM_LED_BLACK_FADE_COMPLETE_BUFFER_MS)
#define THERMOSTAT_ANIM_SPLASH_FADE_OUT_MS 1200
#define THERMOSTAT_ANIM_SPLASH_LINE_SLIDE_MS 400
#define THERMOSTAT_ANIM_SPLASH_LINE_FADE_IN_MS 450
#define THERMOSTAT_ANIM_SPLASH_LINE_ENTER_MS \
  (THERMOSTAT_ANIM_SPLASH_LINE_SLIDE_MS + THERMOSTAT_ANIM_SPLASH_LINE_FADE_IN_MS)
#define THERMOSTAT_ANIM_SPLASH_LINE_FADE_MS 250
#define THERMOSTAT_ANIM_SPLASH_LINE_STAGGER_MS 20
#define THERMOSTAT_ANIM_SPLASH_FINAL_HOLD_MS 1000
#define THERMOSTAT_ANIM_TOP_BAR_STAGGER_MS 100
#define THERMOSTAT_ANIM_TOP_BAR_FADE_MS 600
#define THERMOSTAT_ANIM_TRACK_COOL_GROW_MS 450
#define THERMOSTAT_ANIM_TRACK_HEAT_GROW_MS 300
#define THERMOSTAT_ANIM_TRACK_HEAT_DELAY_MS 150
#define THERMOSTAT_ANIM_TRACK_COOL_END_MS THERMOSTAT_ANIM_TRACK_COOL_GROW_MS
#define THERMOSTAT_ANIM_TRACK_HEAT_END_MS \
  (THERMOSTAT_ANIM_TRACK_HEAT_DELAY_MS + THERMOSTAT_ANIM_TRACK_HEAT_GROW_MS)
#define THERMOSTAT_ANIM_TRACK_END_MS \
  ((THERMOSTAT_ANIM_TRACK_COOL_END_MS > THERMOSTAT_ANIM_TRACK_HEAT_END_MS) \
       ? THERMOSTAT_ANIM_TRACK_COOL_END_MS                                 \
       : THERMOSTAT_ANIM_TRACK_HEAT_END_MS)
#define THERMOSTAT_ANIM_LABEL_FADE_MS 250
#define THERMOSTAT_ANIM_LABEL_FRACTION_DELAY_MS 100
#define THERMOSTAT_ANIM_ACTION_BAR_STAGGER_MS 100
#define THERMOSTAT_ANIM_ACTION_BAR_FADE_MS 300
#define THERMOSTAT_ANIM_ENTRANCE_OFFSET_MS 200
#define THERMOSTAT_ANIM_ENTRANCE_START_DELAY_MS \
  (THERMOSTAT_ANIM_SPLASH_FADE_OUT_MS - THERMOSTAT_ANIM_ENTRANCE_OFFSET_MS)

// Interaction animation timings (milliseconds)
#define THERMOSTAT_ANIM_SETPOINT_COLOR_MS 300
